default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_test
  username: root
  host: localhost
  password: root

test: &test
  <<: *default
  database: ecommerce_test
  username: root
  password: root
  host: localhost

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: ecommerce_test_prod
  username: root
  password: root
  host: localhost
  port: 5432